services:
  - type: web
    name: qreator-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: > PYTHONPATH=. python run.py
    envVars:
      - key: FLASK_ENV
        value: production