services:
  - type: web
    name: qreator-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      PYTHONPATH=. 
      waitress-serve 
      --host=0.0.0.0 
      --port=$PORT 
      run:app
    envVars:
      - key: FLASK_ENV
        value: production